title: alertConfig
x-stoplight:
  id: 8muxxmcyfjcoh
type: object
description: Current alert configuration with thresholds and enable or disable states.
properties:
  ntp:
    type: boolean
    description: Set to true to enable NTP alerts.
    default: false
  userApp:
    type: boolean
    description: Set to true to enable user app alerts.
    default: false
  cpuUsage:
    type: object
    required:
      - treshold
      - status
    properties:
      treshold:
        type: number
        description: Maximum CPU usage percentage before a CPU alert is triggered.
        minimum: 20
        maximum: 100
      status:
        type: boolean
        description: |-
          true - cpu alert enabled
          false - cpu alert disabled
        default: false
  ramUsage:
    type: object
    required:
      - treshold
      - status
    properties:
      treshold:
        type: number
        description: Maximum RAM usage percentage before a RAM alert is triggered.
        minimum: 50
        maximum: 100
      status:
        type: boolean
        description: |-
          true - ram alert enabled 
          false - ram alert disabled
        default: false
  flashUsage:
    type: object
    required:
      - treshold
      - status
    properties:
      treshold:
        type: number
        description: Maximum flash usage percentage before a flash alert is triggered.
        minimum: 40
        maximum: 100
      status:
        type: boolean
        description: |-
          true - flashUsage alert enabled
          false - flashUsage alert disabled
        default: false
  temperature:
    type: object
    required:
      - treshold
      - status
    properties:
      treshold:
        type: number
        description: Maximum temperature before a temperature alert is triggered.
        minimum: 50
        maximum: 100
      status:
        type: boolean
        description: |-
          true - temperature alert enabled
          false - temperature alert disabled        
        default: false
required:
  - ntp
  - userApp